name: 'ume_finops'
version: '1.0.0'
config-version: 2

profile: 'ume_finops'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ume_finops:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table
