import streamlit as st
import sqlite3
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Fintech Credit Analytics", layout="wide", page_icon="💳")

# Connect to database
DB_PATH = "database/ume_finops.db"

@st.cache_data
def load_data(query):
    try:
        conn = sqlite3.connect(DB_PATH)
        df = pd.read_sql(query, conn)
        conn.close()
        return df
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return pd.DataFrame()

# Load Marts
portfolio_df = load_data("SELECT * FROM portfolio_metrics")
reconciliation_df = load_data("SELECT * FROM reconciliation_metrics")
collection_df = load_data("SELECT * FROM collection_metrics")
vintage_df = load_data("SELECT * FROM vintage_default_metrics")
transactions_df = load_data("SELECT * FROM fct_credit_transactions")

# Title
st.title("💳 Fintech Credit Portfolio Dashboard")
st.markdown("Monitor outstanding credit, portfolio health, and collections reconciliation.")

# Section 1 - Portfolio Health
st.header("1. Portfolio Health")

if not portfolio_df.empty:
    metrics = portfolio_df.iloc[0]
    
    # Alert System
    if metrics['par90'] > 0.08:
        st.error(f"🚨 ALERT: PAR90 has exceeded the 8% risk threshold! Current: {metrics['par90']*100:.2f}%")
        
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Outstanding Portfolio", f"R$ {metrics['outstanding_principal']:,.2f}")
    c2.metric("PAR30", f"{metrics['par30']*100:.2f}%")
    c3.metric("PAR90", f"{metrics['par90']*100:.2f}%")
    c4.metric("Average Ticket", f"R$ {metrics['average_ticket']:,.2f}")
else:
    st.info("No portfolio metrics available.")

st.divider()

# Section 2 - Portfolio Evolution
st.header("2. Portfolio Evolution")
if not transactions_df.empty:
    evolution_df = transactions_df.groupby('origination_month')['purchase_value'].sum().reset_index()
    fig1 = px.line(evolution_df, x='origination_month', y='purchase_value', title="Originated Volume by Month", markers=True)
    st.plotly_chart(fig1, use_container_width=True)
else:
    st.info("No transaction data available.")

st.divider()

# Section 3 - Vintage Default Curve
st.header("3. Vintage Default Curve")
if not vintage_df.empty:
    fig2 = px.line(vintage_df, x='origination_month', y='default_rate', title="Default Rate by Origination Cohort", markers=True)
    fig2.update_yaxes(tickformat=".2%")
    st.plotly_chart(fig2, use_container_width=True)
else:
    st.info("No vintage default data available.")
    
st.divider()

# Section 4 - Collections
st.header("4. Collections")
if not collection_df.empty:
    col = collection_df.iloc[0]
    c1, c2 = st.columns(2)
    # Simple bar chart
    expected = col['expected_collection']
    actual = col['actual_collection']
    
    df_bar = pd.DataFrame({
        "Type": ["Expected Collection", "Actual Collection"],
        "Amount": [expected, actual]
    })
    
    fig3 = px.bar(df_bar, x="Type", y="Amount", title="Collections Performance", color="Type")
    # c1 metric
    c1.metric("Collection Rate", f"{col['collection_rate']*100:.2f}%")
    c2.plotly_chart(fig3, use_container_width=True)
else:
    st.info("No collection data available.")
    
st.divider()

# Section 5 - Reconciliation Monitoring
st.header("5. Reconciliation Monitoring")
if not reconciliation_df.empty:
    rec = reconciliation_df.iloc[0]
    
    c1, c2, c3 = st.columns(3)
    c1.metric("Reconciliation Rate", f"{rec['reconciliation_rate']*100:.2f}%")
    c2.metric("Unmatched Payments", f"{int(rec['unmatched_payments'])}")
    c3.metric("Difference (Expected vs Settled)", f"R$ {rec['difference']:,.2f}")
else:
    st.info("No reconciliation data available.")
    
st.caption("Auto-generated by UME FinOps pipeline.")
